version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=boilerplate
      - DB_SSLMODE=disable
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - SERVER_PORT=8080
    networks:
      - boilerplate-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=boilerplate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - boilerplate-network

volumes:
  postgres_data:

networks:
  boilerplate-network:
    driver: bridge